name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          if [ -z "$HF_TOKEN" ]; then
            echo "Error: HF_TOKEN is not set in GitHub Secrets."
            exit 1
          fi
          git push --force https://rachitkumar2105:$HF_TOKEN@huggingface.co/spaces/rachitkumar2105/churn-prediction-api main
